_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.cm.LSUNBedroomAlready
  split: test
  n_samples: 2
  n_skip: 0
  img_size: 256
batch_size: 2
num_workers: 0
collate_fn: 
  _partial_: true
  _target_: dataset.cm.lsun_bedroom_already.custom_collate_fn