_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.cm.CelebAHQDataset
  n_samples: ${exp.n_samples}
  img_size: 256
  path_data: data/celebahq/data
  random_crop: false
  random_flip: true
batch_size: ${exp.batch_size}
num_workers: 0
shuffle: false