model:
  _target_: models.cm.UNetModel
  image_size: 64
  in_channels: 3
  model_channels: 128
  out_channels: 3
  num_res_blocks: 2
  attention_resolutions:
    - 2
    - 4
    - 8
  dropout: 0.0
  channel_mult:
    - 1
    - 2
    - 3 
    - 4
  num_classes: null
  use_checkpoint: false
  use_fp16: false
  num_heads: 4
  num_head_channels: -1
  num_heads_upsample: -1
  use_scale_shift_norm: true
  resblock_updown: false
  use_new_attention_order: false

diffusion:
  _target_: models.cm.KarrasDenoiser
  sigma_data: 0.5
  sigma_max: 80.0
  sigma_min: 0.002
  distillation: false
  weight_schedule: karras