defaults:
  - _self_
  - dataset: cm/imagenet/true_data
  - model: cm/imagenet/corrector_training
  - diffusion: cm/imagenet/corrector_training
  - sampler: cm/imagenet/corrector_training
  - optimizer: cm/imagenet/corrector_training
  - asset: cm/corrector/imagenet/training

exp:
  run_func: 
    _target_: experiment.run_corrector_training
  seed: 42
  log_dir: # set during runtime to automatically created dir

  n_samples: 2048 # indicates dataset size (truncates datasets with bigger size)
  n_epochs: 1_000_000
  batch_size: 64

  eval_freq: 128 # every this number of batches we log qualitative results

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  precision: 16-mixed

wandb:
  project: icm