defaults:
  - _self_
  - model: cm/imagenet/sampling
  - diffusion: cm/imagenet/sampling
  - sampler: ???
  - fid: default
  - dataset@dataset: cm/imagenet/true_data
  - dataset@noise_dataset: cm/imagenet/sampling

exp:
  run_func: 
    _target_: experiment.run_compute_fid
  seed: 42
  log_dir: # set during runtime to automatically created dir

  n_samples: 10240
  batch_size: 512

  grad_at_p: true
  grad_at_c: true
  target_class_id: 339
  ks: [0, 63]
  k: 10
  ts: [0, 40]
  step_size: 0.001
  # TODO return last
  scheduler_type: cos

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1

wandb:
  project: icm