defaults:
  - _self_
  - dataset: cm/lsun_bedroom/sampling
  - model: cm/lsun_bedroom/sampling
  - diffusion: cm/lsun_bedroom/sampling
  - sampler: cm/lsun_bedroom/max_noise

exp:
  run_func: 
    _target_: experiment.run_cm_sampling
  seed: 42
  log_dir: # set during runtime to automatically created dir

  n_samples: 64
  batch_size: 64

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1

wandb:
  project: icm
