_partial_: true
_target_: model.cm.cf_sampler
clf:
  _target_: asset.classifier.ResNet50
step_size: 0.01
k: 20
t_step: 40
t_min: ${diffusion.sigma_min}
t_max: ${diffusion.sigma_max}
rho: ${diffusion.rho}
steps: 201
fix_noise: false