_partial_: true
_target_: model.cm.fixed_noise_scale_sampler
t_step: 200
k: 10
t_min: ${diffusion.sigma_min}
t_max: ${diffusion.sigma_max}
rho: ${diffusion.rho}
steps: 201
fix_noise: false
correction: True