defaults:
  - _self_
  - dataset: 
  - model: cm/imagenet/default

exp:
  run_func: 
    _target_: experiments.run_cm_sampling
  seed: 42
  log_dir: # set during runtime to automatically created dir
  
fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1

wandb:
  project: icm
  use: true